services:
  courses-api:
    build: courses-api
    container_name: courses-api
    restart: always
    networks:
      - edu-plus-network
    ports:
      - "8080:8080"
    depends_on:
      - courses-api-db
  
  comments-api:
    build: comments-api
    container_name: comments-api
    restart: always
    networks:
      - edu-plus-network
    ports:
      - "8081:8081"
    depends_on:
      - comments-api-db
  
  tasks-api:
    build: tasks-api
    container_name: tasks-api
    restart: always
    networks:
      - edu-plus-network
    ports:
      - "8082:8082"
    depends_on:
      - tasks-api-db
  
  users-api:
    build: users-api
    container_name: users-api
    restart: always
    networks:
      - edu-plus-network
    ports:
      - "8083:8083"
    depends_on:
      - users-api-db
  
  api-gateway:
    build: api-gateway
    container_name: api-gateway
    restart: always
    networks:
      - edu-plus-network
    ports:
      - "9000:9000"
  
  courses-api-db:
    image: postgres:16.6
    container_name: courses-api-db
    restart: always
    volumes:
      - courses-api-data:/var/lib/postgresql/data
    networks:
      - edu-plus-network
    environment:
      POSTGRES_USER: courses-api-db
      POSTGRES_PASSWORD: courses-api-db
      POSTGRES_DB: courses-api-db
    ports:
      - "5432:5432"
  
  comments-api-db:
    image: postgres:16.6
    container_name: comments-api-db
    restart: always
    volumes:
      - comments-api-data:/var/lib/postgresql/data
    networks:
      - edu-plus-network
    environment:
      POSTGRES_USER: comments-api-db
      POSTGRES_PASSWORD: comments-api-db
      POSTGRES_DB: comments-api-db
    ports:
      - "5433:5432"
  
  tasks-api-db:
    image: postgres:16.6
    container_name: tasks-api-db
    restart: always
    volumes:
      - tasks-api-data:/var/lib/postgresql/data
    networks:
      - edu-plus-network
    environment:
      POSTGRES_USER: tasks-api-db
      POSTGRES_PASSWORD: tasks-api-db
      POSTGRES_DB: tasks-api-db
    ports:
      - "5434:5432"
  
  users-api-db:
    image: postgres:16.6
    container_name: users-api-db
    restart: always
    volumes:
      - users-api-data:/var/lib/postgresql/data
    networks:
      - edu-plus-network
    environment:
      POSTGRES_USER: users-api-db
      POSTGRES_PASSWORD: users-api-db
      POSTGRES_DB: users-api-db
    ports:
      - "5435:5432"

volumes:
  courses-api-data:
    name: courses-api-data
  comments-api-data:
    name: comments-api-data
  tasks-api-data:
    name: tasks-api-data
  users-api-data:
    name: users-api-data

networks:
  edu-plus-network:
    name: edu-plus-network