spring.application.name=tasks_api

spring.datasource.url=jdbc:postgresql://localhost:5433/tasks-api-db
spring.datasource.username=tasks-api-db
spring.datasource.password=tasks-api-db

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false